version: "3"

services:
  orion_lab:
    image: viadot:orion
    container_name: orion_lab
    ports:
      - 5679:8888
    volumes:
      - ${INFRA_REPO_HOME}/data_platform:/home/viadot
      - ${HOME}/dyvenia/viadot:/home/viadot_local
        # - ${HOME}/.databricks-connect-ext-hive:/home/viadot/.databricks-connect
      - ${HOME}/.databricks-connect:/home/viadot/.databricks-connect
      - ${HOME}/.dbt/profiles.yml:/home/viadot/.dbt/profiles.yml
    shm_size: '4gb'
    command: jupyter lab --no-browser --ip 0.0.0.0 --LabApp.token=''
    restart: "unless-stopped"
