name: "Publish Docker image"
# Publish the viadot Docker image with specified tags.
run-name: "Deploy viadot Docker image with tags: '${{ github.event.inputs.tags }}' by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to use for the image."     
        required: true
        default: "dev"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}       

      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/viadot:${{ github.event.inputs.tag }}
